# Generated by Django 2.2 on 2020-11-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='log_reg.User'),
        ),
    ]
